/**
 * Unified Conversation Message Interface
 * Feature: 005-unified-conversation
 *
 * Defines the unified message type that combines transcription and chat messages
 * Uses discriminated union pattern for type-safe message handling
 */

/**
 * Message sender type
 */
export type MessageSender = 'user' | 'agent';

/**
 * Response mode type (voice or chat)
 */
export type ResponseMode = 'voice' | 'chat';

/**
 * Base message properties shared by all message types
 */
export interface BaseConversationMessage {
  readonly id: string;              // UUID generated by crypto.randomUUID()
  readonly content: string;         // Message text content
  readonly timestamp: Date;         // When message was created/received
  readonly sender: MessageSender;   // 'user' or 'agent'
}

/**
 * Transcription message (from voice/audio)
 * Includes transcription-specific metadata
 */
export interface TranscriptionConversationMessage extends BaseConversationMessage {
  readonly messageType: 'transcription';  // Discriminator field
  readonly confidence?: number;            // Transcription confidence (0-1)
  readonly isFinal: boolean;               // true = final, false = interim
  readonly language?: string;              // Language code (e.g., 'en-US')
}

/**
 * Chat message (from data channel text)
 * Simpler structure for text-only messages
 */
export interface ChatConversationMessage extends BaseConversationMessage {
  readonly messageType: 'chat';           // Discriminator field
  readonly deliveryMethod: 'data-channel'; // Always data-channel for chat
}

/**
 * Unified message type using discriminated union pattern
 * Allows type-safe handling of both transcription and chat messages
 */
export type UnifiedConversationMessage =
  | TranscriptionConversationMessage
  | ChatConversationMessage;

/**
 * Interim transcription state (not yet in message feed)
 * Displayed separately with visual indication
 */
export interface InterimTranscription {
  readonly speaker: MessageSender;  // 'user' or 'agent'
  readonly text: string;            // Current interim text
  readonly timestamp: Date;         // When transcription started
  readonly confidence?: number;     // Optional confidence score
}

/**
 * Type guard for transcription messages
 */
export function isTranscriptionMessage(
  message: UnifiedConversationMessage
): message is TranscriptionConversationMessage {
  return message.messageType === 'transcription';
}

/**
 * Type guard for chat messages
 */
export function isChatMessage(
  message: UnifiedConversationMessage
): message is ChatConversationMessage {
  return message.messageType === 'chat';
}

/**
 * Type guard for valid message sender
 */
export function isValidSender(value: unknown): value is MessageSender {
  return value === 'user' || value === 'agent';
}

/**
 * Factory: Create transcription message from LiveKit transcription event
 */
export function createTranscriptionMessage(
  speaker: MessageSender,
  text: string,
  isFinal: boolean,
  confidence?: number,
  language?: string,
  timestamp: Date = new Date()
): TranscriptionConversationMessage {
  return {
    id: crypto.randomUUID(),
    messageType: 'transcription',
    content: text,
    timestamp,
    sender: speaker,
    confidence,
    isFinal,
    language
  };
}

/**
 * Factory: Create chat message from data channel event
 */
export function createChatMessage(
  sender: MessageSender,
  content: string,
  timestamp: Date | number = new Date()
): ChatConversationMessage {
  return {
    id: crypto.randomUUID(),
    messageType: 'chat',
    content,
    timestamp: typeof timestamp === 'number' ? new Date(timestamp) : timestamp,
    sender,
    deliveryMethod: 'data-channel'
  };
}

/**
 * Factory: Create interim transcription
 */
export function createInterimTranscription(
  speaker: MessageSender,
  text: string,
  confidence?: number
): InterimTranscription {
  return {
    speaker,
    text,
    timestamp: new Date(),
    confidence
  };
}
